JavaScript

* various

標準スクリプト言語の指定
    HTML4.01までは、以下の記述によりonclickなどで使われる標準のスクリプト言語指定が推奨されていたが、
    HTML5ではデフォルトがjavascriptとなり、設定不要に。
    <meta http-equiv="Content-Script-Type" content="text/javascript">

変換
    int.toString(2)  // 2進数へ変換
    int.toString(16) // 16進数へ変換
    parseInt(bin,2)  // 2進⇒10進数へ変換
    parseInt(hex,16) // 16進⇒10進数へ変換

Math
    Math.random  // 0以上1未満の乱数を取得。
    ex:
        Math.floor(Math.random * 10) // 0以上10未満の自然数を取得
        Math.ceil(Math.random * 10)  // 0以上10以下の自然数を取得、気持ち0含まない。

    Math.pow(x,y) // xのyべき乗


* W3C

Syntax
  Loop
    for(;;)
    for( in )
    while()
    do...while()
    break
    continue
    try, catch, throw


Function
  Popup
    alert
    confirm
    prompt


Event
  onload
  onunload
  onfocus
  onblur (when losing focus)
  onchange
  onsubmit
  onmouseover
  onmouseout


Object
  Document
  String
    length
    toUpperCase()
  Date
  Array
  Boolean
  Math
  RegExp
  Navigator


Developer Tool
  Ctrl-Shift-J or F12



* memo

** DOM

*** window

- setInterval
    一定の遅延間隔を置いて関数を繰り返し呼び出す。
    ex: intervalId = window.setInterval(animate, 500)

- clearInterval
    setIntervalを使用して設定された繰り返し動作をキャンセルする。
    ex: window.clearInterval(intervalID)

**** document

- readyState
    読み込み中の場合"loading",
    パースが完了したがサブリソースが読み込み中の場合"inactivate",
    サブリソースの読み込みも完了した時点で"complete"となる。

