* OpenStack

** Release

*** Austin

*** Bexar

*** Cactus

*** Diablo

*** Essex

*** Folsom

*** Grizzly

*** Havana

** Module

*** Nova - Compute
- 
  クラウドコンピューティング・ファブリック（インフラストラクチャー・サービスのコア・コンポーネント）を制御する。
  一般商品化されたサーバリソース（CPU、RAM、ネットワークアダプタ、ハードディスクなど）を仮想化するための中小仮想を作成し、
  リソース使用率を工場させる機能や自動化を促進する機能を提供する。

*** Neutron/Quantum - Networking
- 
  LANの管理機能に加え、VLAN、DHCP、およびIPv6用の機能が組み込まれている。
  ユーザはネットワーク、サブネット、ルータを定義して内部トポロジーを構成し、
  これらのネットワークにIPアドレスとVLANを割り当てることができる。
  さらにフローティングIPアドレスを使用して、VMに対して固定外部IPアドレスの割り当てをすることも出来る。

*** Keystone - Identity Management
- 
  ユーザのディレクトリと、ユーザがアクセスできるOpenStackサービスのカタログを管理する。
  目的は、すべてのOpenStackコンポーネントにわたる中央認証メカニズムを公開すること。
  Keystoneは認証メカニズムそのものを提供するだけでなく、PAM、LDAP、OAuthなどの各ディレクトリサービスを統合できるように設計されている。
  これらプラグインによって、ユーザ名とパスワードをクレデンシャルとして用いた単純な認証システムから
  高度な多要素認証システムにいたるまで、さまざまな認証方式を用意に組み込むことが出来る。

*** Swift - Object Storage
- 
  スケールアウト方式ストレージに最適な冗長ストレージシステム。
  データが複製されプール内のデバイスに分散されることが保証されるため、
  ユーザは高価な装置でなく一般のHDDやサーバを使用できる。
  コンポーネントに障害が発生した場合、他のアクティブなシステムに保管されている内容を新しいクラスタメンバに提供する機能もある。
  水平スケーリングも可能とする。

*** Cinder - Block Storage
- 
  ブロックレベルのストレージを管理する。
  データベースやファイルシステムなど、パフォーマンスに厳しい制約があるシナリオに役立つ。
  もっとも一般的に使用されるストレージはLinuxサーバ・ストレージだが、これ以外のプラットフォーム用プラグインもある。

*** Glance - Image Service
- 
  VMイメージのサポートを提供する。
  厳密に言うと、VMインスタンスを起動する際に使用されるシステムディスクのサポート。
  サービスのディスカバリー、登録、アクティブ化に加え、スナップショット及びバックアップに対処することも出来る。
  

*** Horizon - User Interface Dashboard
- 
  Web管理コンソール

*** Heat
- 
  オーケストレーション機能

*** Ceilometer
- 
  各種コンポーネントのリソース消費量を計測する

*** Trove
- 
  データベースをPaaSとして提供

*** Ironic
- 
  物理サーバのプロビジョニング機能を提供

*** 依存関係
- 

  ┌───────────────────────────┐
  │                     Horizon                          │
  └────────────┬──────────────┘
  ┌──┬─┬───────┼─────────┬────┐
  │    │  │┌──────┴───────┐  │        │
  │    │  ││           Nova             │  │        │
  │    │  │└┬──┬──┬──────┬┘  │        │
  │    │  │  │    │    │            │    │        │
  │    │┌┴─┴─┐│    │            │    │        │
  │    ││ Glance ├┼─┐│            │    │        │
  │    │└─┬──┘│  ││            │    │        │
  │  ┌┴──┴───┴┐││        ┌─┴──┴─┐    │
  │  │    Swift       │││        │  Cinder    │    │
  │  └───┬────┘││        └──┬───┘    │
  │          │          ││              │            │
  └─────┼─────┴┴───────┼──────┘
  ┌─────┴──────┬───────┴──────┐       
  │        Keystone        │           Neutron          │
  └────────────┴──────────────┘


** Link
[[http://www.ibm.com/developerworks/jp/cloud/library/cl-openstack-overview/][- OpenStackについて学ぶ：アーキテクチャー、機能、相互作用]]
