* Operating System
** Role
*** はじめて読む486
**** プロセス管理
- 
  アプリケーションの実行を支援し、管理する機能のこと。

***** マルチタスク
- イベント駆動
  イベントを待つタイミングで他のタスクに切り替える
  完全なマルチタスクでないという意味で「擬似マルチタスク」という。

- プリエンプティブ
  一定時間毎にハードウェア割り込みを発生させる回路を利用して、次のタスクに切り替える。
  「完全なマルチタスク」とも呼ばれる。

**** メモリ管理
- 
  メモリ保護や仮想記憶を実現するには、MMU(Memory Management Unit)と呼ばれるハードウェアが必要。

***** メモリ割り当て
- 
  アプリケーションソフトウェアの要求に応じて、メモリを割り当てたり、回収したりする機能。
  システム領域とユーザ領域に分けられる。

***** メモリ保護
- 
  プログラムからアクセスできるメモリ領域を制限する機能。
  他のアプリケーションのメモリにアクセスできないように制限する。

****** アドレス変換機能
- 
  タスクごとにアドレスの対応を変えることによって、すべてのアドレスを自分のメモリのように使える機能。
  逆に、他のタスクのメモリやOSのメモリにはアクセスできないこととなる。

- MMU(Memory Management Unit)の働き
  アドレス変換はMMUによって実現されている。
  アドレス変換表を内部に持ち、それに沿って送られてきた指示番号のアドレス部分を変換する。
  小さな領域を連続した領域として見せることもできる。

- 論理アドレスと物理アドレス
  MMUを通る前のアドレスが論理アドレス、MMUを通り実際にアクセスするアドレスを物理アドレスという。
  その対応状態をメモリマッピングという。

***** 仮想記憶
- 
  実際に搭載されているよりも多くのメモリ領域があるように見せる機能。
  メモリの内容を主記憶へ退避する事で、より多くのメモリが存在するように見せる。
  MMUにメモリ上にデータが存在するかどうかのフラグがある。

**** ファイルシステム
- 
  ディスク装置などの記憶媒体の管理を支援する機能

**** 入出力管理
- 
  さまざまな周辺機器を接続し、アプリケーションから利用できるようにする機能

*** Wikipedia
**** ハードウェアの抽象化
**** リソースの管理
**** コンピュータの利用効率の向上
** Components
*** Kernel
**** Program execution
**** Interruputs
**** Modes
**** Memory management
**** Virtual memory
**** Multitasking
**** Disk access and file systems
**** Device drivers
*** Networking
*** Security
*** User Interface
** Function
*** Memory Management
*** Protection
*** Process Management
*** Input/Output Management
** Glossary
*** RCU
- read-copy-update
  一種の排他制御を実装する同期機構で、リーダーライターロックの代替手段として使われることがある。

** Link
- [[http://kozos.jp/kozos/index.html][独自OSを作ってみよう！ (KOZOS)]]
