* Ruby

** 初めてのRuby

- オブジェクト
    アイデンティティを持っている
    メッセージを受け取る
    内部状態を持つ

- 型付け
    Rubyは強く型付けされた言語なので、原則的には勝手に他の型にかわることはない。
    to_i, to_s, to_f, to_ioなどが用意されている。
    
.class
    


** [[http://i.loveruby.net/ja/rhg/book/][Rubyソースコード完全解説]]

*** ruby言語ミニマム
- rubyでは全てがオブジェクトで、Javaのintやlongのような基本型(primitive)はない。
- 配列
    [1,2,3]
- ハッシュテーブル
    {"key1"=>"value", "key2"=>"value2"}
- ローカル変数
    小文字から始まる
- 定数
    大文字から始まる
- インスタンス変数
    @から始まる
- 制御
    ifとwhile
- boolean
    falseとnilのみが偽、他は0や空文字も真。
- クラス
    「Stringのupcaseメソッド」→「String#upcase」
    「Object.new」はクラスオブジェクトObjectそれ自体に対して呼ぶメソッドnew、の意味。
    クラスの中にinitializeというメソッドを定義しておくと、newした際に呼んでくれる(newの仕様)
    継承は以下のように書く
       class C < SuperClassName
       end
    省略した場合はObjectがスーパークラスとなる。
    すべてのクラスはObjectクラスを直接または間接に継承する。
- メソッド
    self: 自分自身が誰か、という情報
    自分自身を呼ぶときはself（receiver）を省略できる。
    self.real_my_p(obj)→real_my_p(obj)
- モジュール
    スーパークラスを指定できず、インスタンスも作れないクラス。
    他のクラスにインクルードして使う。
    スーパークラスは継承できないが他のモジュールはインクルードできる。
    クラスとモジュールで同名のメソッドが存在した場合、モジュールが使用される。つまりモジュールの方が近い。



** [[http://docs.ruby-lang.org/ja/2.1.0/doc/index.html][オブジェクト指向スクリプト言語 Ruby リファレンスマニュアル(2.1)]]

*** 組み込みライブラリ
- Ruby本体に組み込まれているライブラリ。
  このライブラリのクラスやモジュールは、requireを書かなくても使うことが出来る。

**** クラス

***** BasicObject
- 継承リスト : BasicObject
- 要約
  特殊な用途のために意図的にほとんど何も定義されていないクラス。
  Ruby 1.9以降で導入された。

***** Object
- 継承リスト : Object < Kernel < BasicObject
- 要約
  全てのクラスのスーパークラス。オブジェクトの一般的な振る舞いを定義する。

***** Class
- 継承リスト : Class < Module  < Object < Kernel < BasicObject
- 要約
  クラスのクラス。多くの機能はモジュールからModuleから継承されている。
- インスタンスメソッド
  - new(*args, &block) -> object
    自身のインスタンスを絵師制して返す。
  - superclass -> Class | nil
    自身のスーパークラスを返す。

***** Module
- 継承リスト : Module < Object < Kernel < BasicObject
- 要約
  モジュールクラス。
- インスタンスメソッド
  - 一覧
    < <= <=> === > >= ancestors autoload autoload? class_eval module_eval class_variable_defined? class_variables
    const_defined? const_get const_missing const_set constants include? include_modules inspect name to_s instance_method
    instance_methods method_defined? prepend private_class_method private_instance_methods private_method_defined?
    protected_instance_metohds protected_method_defined? public_class_method public_instance_method public_instance_methods
    public_method_defined? remove_class_variable

***** Dir
- 継承リスト : Dir < Enumerable < Object < Kernel < BasicObject
- 要約
  ディレクトリの操作を行うためのクラス
- 特異メソッド
  - 一覧
    [] glob chdir chroot delete rmdir unlink entries exist? exists? foreach getwd pwd home mkdir new open
  - glob(pattern, flags = 0) -> [String]
    ワイルドカードの展開を行い、パターンにマッチするファイル名を文字列の配列として返す。
    パターンにマッチするファイルがない場合は空の配列を返す。
    - ワイルドカード
      - * : 空文字列を含む任意の文字列と一致
      - ? : 任意の一文字と一致
      - [] : かぎカッコ内のいずれかの文字と一致。
             -でつながれた文字は範囲を表す。
             最初の文字が^である場合は含まれない文字と一致。同様に!も使える。
      - {} : コンマで区切られた文字列の組み合わせに展開する。
             {foo, bar{foo,bar}}はfoo, barfoo, barbarにマッチする。
      - **/ : ワイルドカード*/の0回以上の繰り返しを意味し、ディレクトリを再帰的にたどってマッチを行う。
              foo/**/barは、foo/bar, foo/*/bar, foo/*/*/bar, ... とマッチする。
- インスタンスメソッド
  - 一覧
    close each inspect path to_path pos tell pos= seek read rewind

**** モジュール

***** Kernel
- 継承リスト : Kernel
- 要約
  全てのクラスから参照できるメソッドを定義しているモジュール。
  トップレベルのメソッドの再定義に対応するため、Objectクラスのメソッドは実際にはこのモジュールで定義されている。





** etc

encoding
    # encoding: utf-8(etc)

local variable
    start with '_' or small alphabet
constant
    start with initialized alphabet
interpolation
    #{} in ""

array
    []
    %w, %W, %i, %I

    insert, delete(_at)
    unshift, << or push
    shift, pop

condition
    if, elsif, else, end
    unless (=> 

puts
gets
    .chomp

print
    文字列を返す。改行文字なし。
p
    読みやすい形にして出力

<=>
    宇宙船演算子

- 数値
    クラス構成
    ・Numeric
        ・Integer
            ・Fixnum
            ・Bignum
        ・Float
    メソッド
        times, upto, downto, step

- 範囲
    Rangeクラス
    1..5は終端を含む。(1,2,3,4,5)
    1...5は終端を含まない。(1,2,3,4)

- 文字列
    ・バックスラッシュ記法
        ""はバックスラッシュ記法を使える、''は使えない。
    ・パーセント記法
        バックスラッシュのエスケープが毎度毎度面倒な時とかに使うらしい。
        %Qは式展開やバックスラッシュ記法を使えるが、%qは使えない。
        ex: str = %q("Ruby", "HTML", "JavaScript", "Rails")
    ・ヒアドキュメント
        開始と終了のラベルとしてキーワードを決め、
        その範囲を文字列オブジェクトとして扱う機能。
        ex:
            print <<EOS
            foo
            bar
            baz
            EOS
            #=>foobarbaz
    メソッド
        +, <<, concat, size, length, empty?, [], split, chomp,
        upcase, downcase, capitalize, swapcase
            
- 正規表現
    /check/ =~ "original"
    %rでも正規表現オブジェクト作成可能
    String#sub(gsub)メソッド
    
- 配列
    Array = [1, 2, 3]
    Array#length
    Array#each
    ・初期化
        Array.new(3, Ruby) #=> ["Ruby", "Ruby", "Ruby"]
    unshift, shift, push, pop, first, last, reverse
    sort, sort_by, each_with_index, inject

- ハッシュ
    キーには文字列かシンボル、値にはオブジェクトが格納できる。
    hash = {"key" => value}
    hash["key"] #=>value
    Hash#delete
    keys, include?, key?, values, value?, clear

- 構文
    until, each, times, for, loop
        break, next, redo

    yield
        ブロック付きメソッド呼び出しの際、ブロック中のプログラムの処理を行う。

    alias
        別名をつける。別名というか、メソッドのコピーみたいな形になるようで、
        元のメソッドの定義を変更しても、別名をつけたメソッドには反映されない。
- モジュール
    module_function

- 特異メソッド
    オブジェクト特有のメソッド。継承されない。
    extendにより定義することも可能。

- ファイル操作等
    入出力
        組み込み定数：STDIN, STDOUT, STDERR
        グローバル変数：$stdin, $stdout, #stderr
    その他クラス・モジュール名
        IO, File, Dir, FileTest
        OperURI(open-uri.rb), Find(find.rb), Pathname(pathname.rb),
        Tempfile(tempfile.rb), FileUtils(fileutils.rb)
    
