* Security

** Vulnerability

*** OS Command Injection

*** XSS / Cross-Site Scripting

*** SQL Injection

*** Code Injection

*** Baffer Error

*** Certification・Password Management

*** CSRF / Cross-Site Request Forjery
- 手順
  1. 攻撃者が、攻撃用のWebページを作成しWWW上に公開する。
  2. 第三者が、攻撃用のWebページにアクセスする。
  3. 第三者は、攻撃者が用意した任意のHTTPリクエストを送信させられる。
  4. 送信させられたHTTPリクエストによって、攻撃者の意図した操作が行われる。

- 対策
  - 利用者
    ログアウトをしてセッションを破棄しておけば、認証段階の手続きが拒否されるので被害が抑えられる。
  - Webサイト作成者側
    - FormをGetする際に、暗号論的擬似乱数値(nonce)を、Cookie値またはセッション、
      およびformのhidden値として発行し、HTTP POST時にその両者の値の同一性を検証する方法がある。
    - HTTP Refererを取得し照合することで、外部からの不正POSTを判別する。
      第三者サイトから、Refererを偽造したPOSTを送信することは不可能。

*** Session Fixation
- 手順
  1. 攻撃者があらかじめWebサイトからCookieとして有効なセッションIDを取得する。
  2. その後ユーザが攻撃者の仕掛けた悪意のWebサイトにアクセスした際、
     事前に手に入れたセッションIDをそのユーザのブラウザに強制的にセットする。
  3. その後第三者がWebサイトにアクセスすることで、セッションIDとユーザ情報が紐付けられ、
     攻撃者がユーザ情報を紐付いたセッションIDを自由に活用できてしまう。
  
- 原因
  Webサーバが発行し、アクセスするたびに値をブラウザが送り出すのが原則だが、
  ブラウザが送ってきたセッションIDが、自分の発行していないにもかかわらず、
  それを有効なセッションIDとして許可してしまうサーバがある場合、問題となる。

** Glossary

*** nonce
- 
  number used onceのことで、1回だけ使われる番号、という意味。
  ワンタイムトークンとも呼ばれる。
  
*** http referer
- 
  HTTPヘッダの1つで、1つのウェブページまたはリソースから見て、
  それにリンクしているウェブページやリソースのアドレスを指す。
  リファラを参照することで、どこからそのページに要求が来たのかを知ることができ、
  プロモーションやセキュリティの目的で使うことができる。
