* ShellScript

** Rule
*** Basics
**** First Line
- 
  #! /bin/sh
  
  use bshell for use every environment.

**** Comment
- 
  use #(sharp).
  comment is from # to end of the line.

**** Line
- 
  line break is the sign of the end of a command in UNIX.
  \(backslash) make ignoring the end sign and connect lines.

**** Wildcard
- 
  * : any characters or none
  ?      : a character
  [...]  : one of the character inside of [...]
  [!...] : one of the character not inside of [...]

- Hidden Files
  handle hidden files using wildcard, you have to write .(dot) explicitely.

**** Quotation
- three ways to Quotate : 
  - \(backslash)
  - '(single quote)
  - "(double quote)
  
- bachslash(\)
  escape-character
  assume a normal character the next of backslash.
  
- single quote '
  in the single quote, all characters are assumed as normal characters.
    
- double quote "
  all characters but $, `(backquote), \(backslash) are assumed as normal characters.
  backslash is work as escape character when next character is $, `, \, " only.
    
- ex
  using variables, sometimes need to use quotation.
  1) 
  STRING=
  test $STRING = john
  (Ë test   = john, error)
    
  STRING=
  test "$STRING" = john
  (Ëtest "" = john, error won't occur)
    
**** Command substitution with backquotes
- 
  backquote substitute command within them to the result of command execution.
  
  - ex)
    $ echo "Today is `date`"
    Ë Today is Sun Nov 23 11:37:33 JST 2015
  
- nest
  being escaped backquote by backslash can perform.
  
  - ex)
  $ STRING=`echo "abc \`echo def\` ghi"`
  $ echo $STRING
  Ë abc def ghi

**** Exit status
- 
  True, Normal : 0
  False, Error : 1

  result is in "$?" variable.

**** Command Separater
- 
  - LineBreak
  - ; (Semicolon)
  - | (Pipe) - make output input of next command
  - & (Ampersand) - excute in background
  - || - OR
  - && - AND

***** Semicolon ;
- 
  executing left to right

***** Pipe |
- 
  vertical line.
  output of the left command on a pipe is processed as input of the right command.

***** Ampersand &
- 
  background execution
  background command gets /dev/null as input.

***** OR Operator ||
- 
  when left command get fail, then right command is executed.

***** AND Operator &&
- 
  when left command get success, then right command is executed.

**** Grouping
***** Parentheses ()
- 
  grouping commands.
  commands in () will execute in subshells.
  environment won't take ovre subshells to parent.

***** Braces {}
- 
  grouping commands.
  unlike parentheses, commands is executed in current shell.
  but when using redirect (like {echo abc} > test.txt), it may be executed in subshell.

**** Control Statement
***** if statement
- format
  if command-list
  then
    command
  else
    command
  fi

***** for statement

***** while statement

***** case statement

***** test statement

**** Line Break and Semicolomn

** Built-in Functions

** Syntax
   
*** $()
- 
  

*** ``
- 
  

